### ISSUE TITLE
Missing functions?

### ISSUE THREAD

**Issue by rtrppl** [DaniruKun/siri-shortcuts.el#3]
What an interesting project! However, after the install I seem to miss all functions to actually execute any shortcut, see screenshot attached. Do you have any idea what the issue could be? During install I got a warning about "misplaced interactive spec" (also see attached). 

![Bildschirmfoto 2021-12-18 um 14 43 11](https://user-images.githubusercontent.com/63909884/146643360-b3bb0739-b48b-4450-b0fe-69e07fc6dd67.png)

![Bildschirmfoto 2021-12-18 um 14 47 34](https://user-images.githubusercontent.com/63909884/146643367-12672a6f-f650-4873-a391-d0e043731ffd.png)

**Comment by DaniruKun** [comment]
Hmm interesting, I did a clean reinstall and checked the byte compile log, are you sure you are using a recent version of Emacs? (`25.2` or newer)?

**Comment by rtrppl** [comment]
Thanks for the reply. I am using: GNU Emacs 27.2 (build 1, arm-apple-darwin20.3.0, NS appkit-2022.30 Version 11.2.3 (Build 20D91)) of 2021-03-27.

**Comment by DaniruKun** [comment]
Hmm maybe it is something ARM Mac specific? Can't reproduce on my x86 one, and nothing shows up in the CI checks. Also tried calling the functions explicitly through `call-interactively`, you can try evaluating the following expression (e.g. using `M-:`) 

```emacs-lisp
(call-interactively #'siri-shortcuts-run)
```

Also try deleting and reinstalling the package if you haven't already, cleaning byte compile cache etc.

**Comment by rtrppl** [comment]
Perhaps it is really ARM specific. I did evaluate the expression and this is what happened:

<img width="787" alt="Bildschirmfoto 2021-12-19 um 12 49 46" src="https://user-images.githubusercontent.com/63909884/146673856-5328dd34-e106-45d7-81fd-28725d08e5a1.png">

I also tried deleting&reinstalling the package, to no avail.

**Comment by DaniruKun** [comment]
Hmm very strange. I'll try to ask some more people with ARM Macs to try this out.

**Comment by danirukun** [comment]
@rtrppl it was a bug with the way command declaration was setup, thanks for reporting! It should be fixed now in version `0.3`. If the issue persists, please let me know and I will reopen.
